import { IFieldCell } from '../types'

const GAME_FIELD: IFieldCell[][] = [
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/mountain.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/ruins.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/ruins.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/mountain.png' },
    { id: 10, image: '/images/other/ruins.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/mountain.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/ruins.png' },
    { id: 3, image: '/images/other/mountain.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/ruins.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/ruins.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/mountain.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
]

export { GAME_FIELD }
