import { IFieldCell } from '../types'

const GAME_POINTS_CARDS = {
  city: [
    '/images/points_card/city_1.png',
    '/images/points_card/city_2.png',
    '/images/points_card/city_3.png',
    '/images/points_card/city_4.png',
  ],
  wood: [
    '/images/points_card/wood_1.png',
    '/images/points_card/wood_2.png',
    '/images/points_card/wood_3.png',
    '/images/points_card/wood_4.png',
  ],
  fields: [
    '/images/points_card/fields_1.png',
    '/images/points_card/fields_2.png',
    '/images/points_card/fields_3.png',
    '/images/points_card/fields_4.png',
  ],
  form: [
    '/images/points_card/form_1.png',
    '/images/points_card/form_2.png',
    '/images/points_card/form_3.png',
    '/images/points_card/form_4.png',
  ],
}

const DECK_OF_CARDS = [
  '/images/cards/card_1.png',
  '/images/cards/card_2.png',
  '/images/cards/card_3.png',
  '/images/cards/card_4.png',
  '/images/cards/card_5.png',
  '/images/cards/card_6.png',
  '/images/cards/card_7.png',
  '/images/cards/card_8.png',
  '/images/cards/card_9.png',
  '/images/cards/card_10.png',
  '/images/cards/card_11.png',
  '/images/cards/card_12.png',
  '/images/cards/card_13.png',
]

const DECK_OF_ENEMY_CARDS = [
  '/images/cards/enemy_card_1.png',
  '/images/cards/enemy_card_2.png',
  '/images/cards/enemy_card_3.png',
  '/images/cards/enemy_card_4.png',
]

const GAME_FIELD: IFieldCell[][] = [
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/mountain.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/ruins.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/ruins.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/mountain.png' },
    { id: 10, image: '/images/other/ruins.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/mountain.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/ruins.png' },
    { id: 3, image: '/images/other/mountain.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/ruins.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/ruins.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/mountain.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
  [
    { id: 1, image: '/images/other/cell.png' },
    { id: 2, image: '/images/other/cell.png' },
    { id: 3, image: '/images/other/cell.png' },
    { id: 4, image: '/images/other/cell.png' },
    { id: 5, image: '/images/other/cell.png' },
    { id: 6, image: '/images/other/cell.png' },
    { id: 7, image: '/images/other/cell.png' },
    { id: 8, image: '/images/other/cell.png' },
    { id: 9, image: '/images/other/cell.png' },
    { id: 10, image: '/images/other/cell.png' },
    { id: 11, image: '/images/other/cell.png' },
  ],
]

export { GAME_FIELD, GAME_POINTS_CARDS, DECK_OF_CARDS, DECK_OF_ENEMY_CARDS }
