const OK = 200
const BAD_REQUEST = 400
const INTERNAL_ERROR = 500
const UNAUTHORIZED = 401
const FORBIDDEN = 403
const NOT_FOUND = 404

export { OK, BAD_REQUEST, INTERNAL_ERROR, UNAUTHORIZED, FORBIDDEN, NOT_FOUND }
